language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements-test.txt"
# command to run tests
script:
  - "flake8 ."
  - "nosetests -v test/"
  - "sh docker/build.sh"
sudo: required
services:
  - docker