language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
# command to run tests
script:
  - flake8 .
  - nosetests -v
notifications:
  irc:
    channels:
      - "irc.esper.net#Ultros"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"