language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - pip install flake8
# command to run tests
script: flake8 .
notifications:
  irc:
    channels:
      - "irc.esper.net#Ultros"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"